name: zCloud CLI test
on:
  push:
    branches: ['main']

jobs:
  deploy-apps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: zcloud-ws/zcloud-deploy-action@main
        with:
          user-token: ${{ secrets.ZCLOUD_USER_TOKEN }}
          env: joaovictornsv-local-list-dev
