name: zCloud CLI Preview
on:
  pull_request:
    branches: ['main']

jobs:
  deploy-apps:
    env:
      __ZCLOUD_INTERNAL_API_CLIENT_URI: 'https://api.zcloud.land'
      __ZCLOUD_INTERNAL_ENV: 'staging'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: zcloud-ws/zcloud-deploy-action@main
        with:
          user-token: ${{ secrets.ZCLOUD_USER_TOKEN_STAGING }}
          dir: .
          cli-extra-args: '--app local-list-cli --zclouds 2 --create'
